#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: vault-readonly-secrets-binding
#subjects:
#- kind: ServiceAccount
#  name: vault-secrets-operator
#  namespace: vault-secrets-operator   # only this SA in this namespace
#roleRef:
#  kind: ClusterRole
#  name: vault-readonly-secrets
#  apiGroup: rbac.authorization.k8s.io