- name: Copy network script
  copy:
    src: "{{ item }}"
    dest: /home/{{USER}}/{{PROJECT_PATH}}/k8s/v{{KUBERNETES_VERSION}}/
  with_fileglob:
    - "*"

- name: Run network script
  become: true
  shell: bash /home/{{USER}}/{{PROJECT_PATH}}/k8s/v{{KUBERNETES_VERSION}}/3_configure_network.sh

- name: Run firewalld script
  become: true
  shell: bash /home/{{USER}}/{{PROJECT_PATH}}/k8s/v{{KUBERNETES_VERSION}}/4-configure_firealld_selinux.sh

- name: Disable apparmor
  become: true
  ansible.builtin.systemd:
    name: apparmor
    enabled: no
    state: stopped
