installCRDs: true
global:
  domain: argocd.maifuj.com
configs:
  params:
    server.insecure: true
  secret:
    argocdServerAdminPassword: "{{ ARGOCD_ADMIN_PASSWORD_HASH }}"
applicationSet:
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
controller:
  priorityClassName: "system-cluster-critical"
  resources:
    limits:
      cpu: 500m
      memory: 1.5Gi
    requests:
      cpu: 100m
      memory: 1.5Gi
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
dex:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
redis:
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
repoServer:
  priorityClassName: "system-cluster-critical"
  resources:
    requests:
      cpu: 100m
      memory: 700Mi
    limits:
      memory: 750Mi
      cpu: 500m
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
server:
  priorityClassName: "system-cluster-critical"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 150Mi
      cpu: 500m
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master
notifications:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: master