- hosts: k8s-master
  become: false
  vars_files:
    - /home/ubuntu/k8s_aws_lite/ansible/apps/default-apps/group_vars/all/vault.yml   # vaulted file
  vars:
    PROJECT_PATH: k8s_aws_lite   # File will be  created at home directory
    KUBERNETES_MAJOR_VERSION: v1.32
    KUBERNETES_VERSION: v1.36.2  # add 'v' in at prefix whenever required.
    PACKAGE_DIRECTORY: packages
    USER: ubuntu
    MASTER_NODE_IP: 172.31.64.40
    WORKER_1_NODE_IP: 172.31.64.41
    WORKER_2_NODE_IP: 172.31.64.42
    KUBECONFIG_PATH: "/home/ubuntu/.kube/config"
  roles:
    - default-apps
