apiVersion: v1
kind: LimitRange
metadata:
  name: kiali-limit-range
  namespace: kiali
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      default:
        cpu: 300m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: 1
        memory: 1536Mi