- name: Create package folder
  file:
    path: /home/{{USER}}/{{PROJECT_PATH}}/v{{KUBERNETES_VERSION}}/{{PACKAGE_DIRECTORY}}/
    state: directory
    mode: "755"
    recurse: true

- name: Remove old Kubernetes GPG key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: Download Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_MAJOR_VERSION }}/deb/Release.key -o /home/{{USER}}/{{PROJECT_PATH}}/v{{KUBERNETES_VERSION}}/{{PACKAGE_DIRECTORY}}/kubernetes-gpg.asc;

- name: Check if gpg file exists
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: file_exists

- name: Add kubernetes GPG key
  become: true
  shell: |
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /home/{{USER}}/{{PROJECT_PATH}}/v{{KUBERNETES_VERSION}}/{{PACKAGE_DIRECTORY}}/kubernetes-gpg.asc
  when: not file_exists.stat.exists

- name: Add k8s repos
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_MAJOR_VERSION }}/deb/ /"
    state: present

- name: Update APT package index after adding Kubernetes repo
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubernetes components (kubelet, kubeadm, kubectl)
  become: true
  ansible.builtin.apt:
    name:
      - "kubelet={{ KUBERNETES_VERSION }}*"
      - "kubeadm={{ KUBERNETES_VERSION }}*"
    state: present
    update_cache: yes
    allow_downgrades: yes

- name: Prevent Kubernetes components from being automatically upgraded
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
