apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: app
  namespace: book-info
spec:
  gateways: ["istio-ingress/gateway-https"]
  hosts: ["bookinfo.maifuj.com"]
  http:
    - route:
        - destination:
            host: productpage
            port: {number: 9080}