apiVersion: v1
kind: LimitRange
metadata:
  name: rook-ceph-limitrange
  namespace: rook-ceph
spec:
  limits:
    - type: Container
      defaultRequest:        # applied if requests are omitted
        cpu: 10m
        memory: 64Mi
      default:               # applied if limits are omitted
        cpu: 300m
        memory: 512Mi
      min:                   # optional: reject anything below this
        cpu: 10m
        memory: 32Mi
      max:                   # optional: reject anything above this
        cpu: 1
        memory: 1024Mi