apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager-datasource
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  allowCrossNamespaceImport: true
  datasource:
    name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://vmalertmanager-vm-dev-victoria-metrics-k8s-stack.vm.svc.cluster.local.:9093
    isDefault: false
    jsonData:
      timeInterval: "30s"
      httpMethod: POST
      tlsSkipVerify: true