apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server-appset
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - matrix:
        generators:
          - git:
              repoURL: https://github.com/maifujalam/k8s_aws_lite.git
              revision: main
              files:
                - path: k8s/v1.36.2/clusters/*/metrics-server/appset-config.yaml
          - clusters:
              selector:
                matchLabels:
                  cluster-name: '{{ index .path.segments 3}}'
  template:
    metadata:
      name: '{{ index .path.segments 4}}-{{ index .path.segments 3}}'
      labels:
        app: '{{ index .path.segments 4}}'
        cluster-name: '{{ index .path.segments 3}}'
    spec:
      project: dev-project
      sources:
        - repoURL: https://kubernetes-sigs.github.io/metrics-server/
          targetRevision: '{{.chart_version}}'
          chart: '{{.chart_name}}'
          helm:
            valueFiles:
              - $values/{{.path.path}}/helm-config.yaml
            skipCrds: true
        - repoURL: https://github.com/maifujalam/k8s_aws_lite.git
          targetRevision: main
          ref: values
#         - repoURL: https://github.com/maifujalam/k8s_aws_lite.git
#           targetRevision: main
#           path: k8s/v1.36.2/clusters/dev/<sample-app>/kubernetes-objects
#           directory:
#             recurse: true
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true