Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 2048
    libvirt.cpus = 2

    # Disable automatic NIC Creating
    libvirt.mgmt_attach = false
  end

  config.vm.network "private_network",
    type: "dhcp",
    libvirt__network_name: "vm-nat",
    libvirt__always_destroy: false

  config.vm.network "private_network",
    ip: "192.168.100.10",
    libvirt__network_name: "vm-local",
    libvirt__always_destroy: false
end