apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: icmp-external
  namespace: blackbox-exporter
spec:
  vmProberSpec:
     url: blackbox-exporter-dev-prometheus-blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
  module: icmp
  targets:
   static:
      targets:
      - 13.207.12.184
      - 8.8.8.8
  interval: 10s