- name: Download crictl Binary
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.36.0/crictl-v1.36.0-linux-amd64.tar.gz
    dest: /tmp/crictl-v1.36.0-linux-amd64.tar.gz
    mode: '0644'

- name: Extract crictl Binary
  become: true
  unarchive:
    src: /tmp/crictl-v1.36.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Copy crictl config
  become: true
  copy:
    src: crictl.yaml
    dest: /etc/


- name: Copy containerd config
  become: true
  copy:
    src: config.toml
    dest: /etc/containerd/

- name: Enable and restart containerd service
  become: true
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: restarted

