replicaCount: 1

image:
  repository: harbor.maifuj.com/dev-apps/default-backend
  tag: 9
  pullPolicy: IfNotPresent

service:
  name: default-backend
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 16Mi

gateway:
  names:
    - istio-ingress/gateway-https
    - istio-ingress/gateway-tls-passthrough
  hosts:
    - "*.maifuj.com"

nodeSelector:
  kubernetes.io/hostname: master
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"