---
- hosts: k8s-master
  become: false
  vars:
    PROJECT_PATH: nuc # File will be  created at home directory
    KUBERNETES_MAJOR_VERSION: v1.37
    KUBERNETES_VERSION: 1.37.0  # add 'v' in at prefix whenever required.
    USER: vagrant
    MASTER_NODE_IP: 192.168.100.10
  roles:
    - download-packages
    - configure_node
    - bootstrap_k8s_master
