awsAccessSecret:
  name: aws-secret
  keyId: key_id
  accessKey: access_key
controller:
  defaultFsType: ext4
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      memory: 256Mi
  serviceAccount:
    create: true
    name: ebs-csi-controller-sa
    automountServiceAccountToken: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
      tolerationSeconds: 300
storageClasses:
- name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app: aws-ebs-csi-driver
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Retain  # Or Delete
  parameters:
    encrypted: "true"
defaultStorageClass:
  enabled: true
