# ansible-galaxy collection install -r requirements.yaml
collections:
  - name: community.kubernetes
    version: 2.0.1  # Optional: specify version
  - name: ansible.posix  # Install another collection
    version: 2.2.2  # Optional: specify version
