#apiVersion: networking.istio.io/v1
#kind: Gateway
#metadata:
#  name: gateway-grpc
#  namespace: istio-ingress
#spec:
#  selector:
#    istio: ingress-dev
#  servers:
#    - port: {number: 80, name: http, protocol: HTTP}
#      hosts: ["*.maifuj.com"]
#      tls:
#        httpsRedirect: true      # 301 to https, no VirtualService needed
#    - port: {number: 443, name: https, protocol: HTTPS}
#      hosts: ["*.maifuj.com"]
#      tls:
#        mode: SIMPLE
#        credentialName: wildcard-certificate-secret