---
- hosts: k8s-worker-2
  become: false
  vars:
    PROJECT_PATH: k8s_aws_lite  # File will be  created at home directory
    KUBERNETES_MAJOR_VERSION: v1.37
    KUBERNETES_VERSION: 1.37.0  # add 'v' in at prefix whenever required.
    PACKAGE_DIRECTORY: packages
    USER: vagrant
    MASTER_NODE_IP: 192.168.100.10
    WORKER_NODE_IP: 192.168.100.12
  roles:
    - download-packages
    - configure_node
    - bootstrap_k8s_worker
