apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: my-default-static-secret
  namespace: default
spec:
  type: kv-v2
  mount: secrets               # KV engine mount path in Vault
  path: dev/default                 # secret path inside the KV engine
  destination:
    name: my-k8s-default-secret
    create: true
  refreshAfter: 10s
  vaultAuthRef: default   # reference your VaultAuth
