apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: default
spec:
  type: kv-v2   # type of the secret engine
  mount: secrets # mount path of the secret engine
  path: config   # path of the secret
  destination:   # destination of the secret to be created inside kubernetes cluster
    name: mysecrets  # name of the kubernetes secret to be created.
    create: true     # create the kubernetes secret if it does not exist.
  refreshAfter: 10s   # static secret refresh interval
  vaultAuthRef: static-auth   # Name of the CRD to authenticate to Vault
  syncConfig:
    instantUpdates: true  # instant updates to the kubernetes secret when the vault secret is updated.
