apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vault-dynamic-secret
  namespace: default
spec:
  mount: secrets # mount path of the secret engine
  path: config   # path of the secret
  destination:   # destination of the secret to be created inside kubernetes cluster
    name: mysecrets-dynamic  # name of the kubernetes secret to be created.
    create: true     # create the kubernetes secret if it does not exist.
  # Restart these pods when secrets rotated
  rolloutRestartTargets:
    - kind: Deployment
      name: nginx
  vaultAuthRef: dynamic-auth  # Name of the CRD to authenticate to Vault
